### PR TITLE
Add compression params : always . It now only accepts "always", "meta…

### PR DESCRIPTION
**Pull request by bigbigbang**
Add compression params : always . It now only accepts "always", "metadata" or "false"(default)

### CODE REVIEW

**Comment by bigbigbang** [comment]
better : 
`<%- if (@compression == 'always' or @compression =='metadata')-%><%= @compression%><%- else -%>false<%- end -%>'`
Don't know why I wanted to regex this string.. :P

**Comment by mateusz-gozdek-sociomantic** [comment]
As far as I remember @whefter didn't want to validate parameters at all, but maybe just
```
<%= ['metadata','always'].include? @compression ? @compression : 'false' %>
``` 
Shortest and cleaned solution IMO.

Edit:
switched from `in?` to `include?` as `in?` is Rails function.

**Comment by bigbigbang** [comment]
Yes, but here it's not validation, we miss one option if we only authorize "true" or "false" (as we can choose "metadata" or "always").

**Comment by whefter** [comment]
Ah, thanks. Yeah, I'd have just removed the if check completely. In my experience it won't be long before someone puts in "METADATA" and complains it turns out to be false. But we'll deal with that when it occurs.

**Pull request merged**
