### PR TITLE
Correct folders option/add option to add several globalAnnounceServer and to disable defaults

### PR DESCRIPTION
**Pull request by bigbigbang**
add folders type for readonly, autoNormalize reflecting new syncthing parameters.
Add global option to add several GlobalAnnounceServer and to disable the defaults provided. (This is when you want to be "isolated" from public instance)

### CODE REVIEW

**Comment by bigbigbang** [comment]
deleted previous PR , was too messy ^

**Comment by mateusz-gozdek-sociomantic** [comment]
Few advices:
- if you create PR on GitHub, you should use feature-branch, so later on you can merge it to upstream project master, instead of merging master-master
- if you have feature-branch, you can make force-push to PR to override pushed changes. This way you can rebase your PR to clean up the workflow history
- you shouldn't push merge commits, GitHub will take care of it

**Comment by bigbigbang** [comment]
ok thx for advices ^ will create my branch next time :)

**Comment by bigbigbang** [comment]
still having some issues ^^ I' m  working on it ^^ don't merge it :)

**Pull request closed without merging**
